[package]
name = "wpp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { features = ["macros"], default-features = false, version = "4.9.0" }
anyhow = { default-features = false, version = "1.0.95" }
bcrypt = { features = ["std"], default-features = false, version = "0.17.0" }
chrono = { default-features = false, version = "0.4.39" }
dotenv = "0.15.0"
jsonwebtoken = { default-features = false, version = "9.3.0" }
mongodb = "3.2.0"
serde = { version = "1.0.217", default-features = false }

[build]
rustflags = ["-Z", "threads=8"]
